[package]
name = "auth"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
argon2 = { workspace = true }
chrono = { workspace = true }
jsonwebtoken = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
