openapi: 3.0.3
info:
  title: Chat Service API
  description: |
    Real-time messaging service for chat-rs.

    Handles channel management, message persistence, and real-time message delivery.
  version: 0.1.0
  contact:
    name: chat-rs
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

tags:
  - name: channels
    description: Channel management operations
  - name: messages
    description: Message operations
  - name: websocket
    description: Real-time connection management

paths:
  /api/channels:
    post:
      tags:
        - channels
      summary: Create a new channel
      description: Creates a public, private, or direct message channel
      operationId: createChannel
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/CreatePublicChannelRequest'
                - $ref: '#/components/schemas/CreatePrivateChannelRequest'
                - $ref: '#/components/schemas/CreateDirectChannelRequest'
              discriminator:
                propertyName: channel_type
      responses:
        '200':
          description: Channel created successfully
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/PublicChannel'
                  - $ref: '#/components/schemas/PrivateChannel'
                  - $ref: '#/components/schemas/DirectChannel'
        '401':
          description: Unauthorized - Invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Conflict - Channel name already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Unprocessable Entity - Validation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    get:
      tags:
        - channels
      summary: List public channels
      description: Retrieves a list of all public channels
      operationId: listPublicChannels
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of public channels
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PublicChannel'
        '401':
          description: Unauthorized - Invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/channels/{id}:
    get:
      tags:
        - channels
      summary: Get channel by ID
      description: Retrieves channel details
      operationId: getChannelById
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: Channel UUID
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Channel found
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/PublicChannel'
                  - $ref: '#/components/schemas/PrivateChannel'
                  - $ref: '#/components/schemas/DirectChannel'
        '401':
          description: Unauthorized - Invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Channel not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/channels/{id}/messages:
    get:
      tags:
        - messages
      summary: Get channel messages
      description: Retrieves messages for a channel with pagination
      operationId: getChannelMessages
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: Channel UUID
          schema:
            type: string
            format: uuid
        - name: limit
          in: query
          description: Maximum number of messages to return
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 50
        - name: before
          in: query
          description: Return messages before this timestamp (ISO 8601)
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: List of messages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
        '400':
          description: Bad Request - Invalid parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - Invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /ws:
    get:
      tags:
        - websocket
      summary: WebSocket connection endpoint
      description: |
        Establishes a persistent WebSocket connection for real-time message delivery.

        **Connection:**
        - URL: `ws://localhost:3002/ws?token={jwt_token}`
        - Protocol: WebSocket

        **Client → Server Messages:**
        ```json
        {
          "type": "subscribe",
          "channel_id": "550e8400-e29b-41d4-a716-446655440000"
        }
        ```

        **Server → Client Messages:**
        ```json
        {
          "type": "new_message",
          "id": "...",
          "channel_id": "...",
          "user_id": "...",
          "username": "john_doe",
          "content": "Hello world!",
          "timestamp": "2024-01-15T10:30:00Z"
        }
        ```
      parameters:
        - name: token
          in: query
          required: true
          description: JWT token for authentication
          schema:
            type: string
      responses:
        '101':
          description: Switching Protocols - WebSocket connection established
        '401':
          description: Unauthorized - Invalid or missing token
        '400':
          description: Bad Request - WebSocket upgrade failed

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from user-service /api/auth/login

  schemas:
    CreatePublicChannelRequest:
      type: object
      required:
        - channel_type
        - name
      properties:
        channel_type:
          type: string
          enum: [public]
          description: Channel type
        name:
          type: string
          minLength: 3
          maxLength: 50
          pattern: '^[a-zA-Z0-9-]+$'
          description: Channel name (alphanumeric with hyphens)
          example: general-discussion
        description:
          type: string
          maxLength: 500
          description: Optional channel description
          example: General discussion channel

    CreatePrivateChannelRequest:
      type: object
      required:
        - channel_type
        - name
      properties:
        channel_type:
          type: string
          enum: [private]
          description: Channel type
        name:
          type: string
          minLength: 3
          maxLength: 50
          pattern: '^[a-zA-Z0-9-]+$'
          description: Channel name (alphanumeric with hyphens)
          example: team-announcements
        description:
          type: string
          maxLength: 500
          description: Optional channel description

    CreateDirectChannelRequest:
      type: object
      required:
        - channel_type
        - participant_id
      properties:
        channel_type:
          type: string
          enum: [direct]
          description: Channel type
        participant_id:
          type: string
          format: uuid
          description: UUID of the other participant
          example: 550e8400-e29b-41d4-a716-446655440000

    PublicChannel:
      type: object
      required:
        - id
        - type
        - name
        - created_by
        - created_at
      properties:
        id:
          type: string
          format: uuid
          description: Channel unique identifier
          example: 550e8400-e29b-41d4-a716-446655440000
        type:
          type: string
          enum: [public]
          description: Channel type
        name:
          type: string
          description: Channel name
          example: general-discussion
        description:
          type: string
          description: Channel description
          example: General discussion channel
        created_by:
          type: string
          format: uuid
          description: User ID of channel creator
          example: 660e8400-e29b-41d4-a716-446655440000
        created_at:
          type: string
          format: date-time
          description: Channel creation timestamp
          example: '2024-01-15T10:30:00Z'

    PrivateChannel:
      type: object
      required:
        - id
        - type
        - name
        - created_by
        - created_at
      properties:
        id:
          type: string
          format: uuid
          description: Channel unique identifier
        type:
          type: string
          enum: [private]
          description: Channel type
        name:
          type: string
          description: Channel name
        description:
          type: string
          description: Channel description
        created_by:
          type: string
          format: uuid
          description: User ID of channel creator
        created_at:
          type: string
          format: date-time
          description: Channel creation timestamp

    DirectChannel:
      type: object
      required:
        - id
        - type
        - created_by
        - created_at
      properties:
        id:
          type: string
          format: uuid
          description: Channel unique identifier
        type:
          type: string
          enum: [direct]
          description: Channel type
        created_by:
          type: string
          format: uuid
          description: User ID of channel creator
        created_at:
          type: string
          format: date-time
          description: Channel creation timestamp

    Message:
      type: object
      required:
        - id
        - channel_id
        - user_id
        - content
        - timestamp
      properties:
        id:
          type: string
          format: uuid
          description: Message unique identifier (time-based UUID)
          example: 6ba7b810-9dad-11d1-80b4-00c04fd430c8
        channel_id:
          type: string
          format: uuid
          description: Channel where message was sent
          example: 550e8400-e29b-41d4-a716-446655440000
        user_id:
          type: string
          format: uuid
          description: User who sent the message
          example: 660e8400-e29b-41d4-a716-446655440000
        username:
          type: string
          description: Username of sender (enriched from user replica)
          example: john_doe
        content:
          type: string
          minLength: 1
          maxLength: 5000
          description: Message content
          example: Hello, world!
        timestamp:
          type: string
          format: date-time
          description: Message timestamp
          example: '2024-01-15T10:30:00Z'

    WebSocketSubscribeMessage:
      type: object
      required:
        - type
        - channel_id
      properties:
        type:
          type: string
          enum: [subscribe]
          description: Message type
        channel_id:
          type: string
          format: uuid
          description: Channel to subscribe to
          example: 550e8400-e29b-41d4-a716-446655440000

    WebSocketNewMessage:
      type: object
      required:
        - type
        - id
        - channel_id
        - user_id
        - content
        - timestamp
      properties:
        type:
          type: string
          enum: [new_message]
          description: Message type
        id:
          type: string
          format: uuid
          description: Message ID
        channel_id:
          type: string
          format: uuid
          description: Channel ID
        user_id:
          type: string
          format: uuid
          description: Sender user ID
        username:
          type: string
          description: Sender username
          example: john_doe
        content:
          type: string
          description: Message content
          example: Hello, world!
        timestamp:
          type: string
          format: date-time
          description: Message timestamp
          example: '2024-01-15T10:30:00Z'

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error message
          example: Channel not found
